<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>inabif</groupId>
		<artifactId>business-domain</artifactId>
		<version>1.0</version>
	</parent>

	<groupId>microservice</groupId>
	<artifactId>sigesu</artifactId>
	<version>1.0</version>
	<packaging>jar</packaging>
	<name>sigesu</name>
	<description>...</description>

	<dependencies>

		<dependency>
			<groupId>microservice</groupId>
			<artifactId>shared-data</artifactId>
			<version>1.0</version>
		</dependency>

		<dependency>
			<groupId>com.itextpdf</groupId>
			<artifactId>itext7-core</artifactId>
			<version>7.2.3</version>
			<type>pom</type>
		</dependency>

		<dependency>
			<groupId>com.github.librepdf</groupId>
			<artifactId>openpdf</artifactId>
			<version>1.3.30</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<outputDirectory>${output.dir}</outputDirectory>
				</configuration>
			</plugin>
		</plugins>
	</build>


</project>