# ======================================================================================================
# 1. PROPS BASE
# ======================================================================================================
server:
   port: ${PORT:5000}

spring:
   application:
      name: ms-scheduling
   profiles:
      active: ${PROFILE:prod}

   datasource:
      hikari:
         # Configuración clave para reintentos
         initialization-fail-timeout: -1  # No fallar al inicio
         connection-timeout: 60000
         validation-timeout: 5000
         
         # Pool de conexiones
         maximum-pool-size: 20
         minimum-idle: 5
         idle-timeout: 300000
         max-lifetime: 1200000
         leak-detection-threshold: 60000

# ======================================================================================================
# 2. CONTROL DE SCHEDULERS
# ======================================================================================================
schedulers:
   enabled: true
   punche: # ? » Familias Igualitarias
      enabled: true
      output-path: reports/familias-igualitarias/
      matriz:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/matriz
            excel:
               enabled: false
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_matriz
               cron: '0 0 8 * * *' # ? 08:00 AM
      intervenciones-estrategicas:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/intervenciones-estrategicas
            excel:
               enabled: false
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_intervenciones_estrategicas
               cron: '0 0 8 * * *' # ? 08:00 AM
      diagnostico-familiar:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/diagnostico-familiar/reportes
            excel:
               enabled: false
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_ficha_diagnostico_familiar
               cron: '0 3 8 * * *' # ? 08:00 AM
      ffsil:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/ffsil/reportes
            excel:
               enabled: false
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_ficha_ffsil
               cron: '0 6 8 * * *' # ? 08:00 AM
      tsv:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/tsv/reportes
            excel:
               enabled: false
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_ficha_tsv
               cron: '0 9 8 * * *' # ? 08:00 AM
      encuesta-satisfaccion:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/encuesta-satisfaccion/reportes
            excel:
               enabled: false
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_ficha_encuesta_satisfaccion
               cron: '0 11 8 * * *' # ? 08:00 AM
      prog-sesion:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/prog-sesion
            excel:
               enabled: true
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_prog_sessiones
               cron: '0 0 6 * * *' # ? 06:00 AM
      prog-taller:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/prog-taller
            excel:
               enabled: true
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_prog_talleres
               cron: '0 0 6 * * *' # ? 06:00 AM
   siges: # ? » SIGES
      enabled: true
      output-path: reports/siges/
      matriz_fichas_siges:
         enabled: true
         report:
            output-path: ${schedulers.siges.output-path}/matriz-fichas-siges
            excel:
               enabled: true
               output-path: ${schedulers.siges.output-path}/excel/
               file-name: rpt_matriz_fichas_siges
               cron: '0 0 6 * * *' # ? 08:00 AM

# ======================================================================================================