# ======================================================================================================
# 1. PROPS BASE
# ======================================================================================================
server:
   port: ${PORT:5000}

spring:
   application:
      name: ms-scheduling
   profiles:
      active: ${SPRING_PROFILE:dev}

   datasource:
      url: jdbc:oracle:thin:@172.19.0.42:1521:INABIF02
      username: devuser
      password: D3vUs3r$2025
      driver-class-name: oracle.jdbc.OracleDriver

# ======================================================================================================
# 2. CONTROL DE SCHEDULERS
# ======================================================================================================
schedulers:
   enabled: true
   punche: # ? » Familias Igualitarias
      enabled: true
      output-path: reports/familias-igualitarias/
      intervenciones-estrategicas:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/intervenciones-estrategicas
            excel:
               enabled: true
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_intervenciones_estrategicas
               cron: '0 0 8 * * *' # ? 08:00 AM
      diagnostico-familiar:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/diagnostico-familiar/reportes
            excel:
               enabled: true
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_ficha_diagnostico_familiar
               cron: '0 3 8 * * *' # ? 08:00 AM
      ffsil:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/ffsil/reportes
            excel:
               enabled: true
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_ficha_ffsil
               cron: '0 6 8 * * *' # ? 08:00 AM
      tsv:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/tsv/reportes
            excel:
               enabled: true
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_ficha_tsv
               cron: '0 9 8 * * *' # ? 08:00 AM
      encuesta-satisfaccion:
         enabled: true
         report:
            output-path: ${schedulers.punche.output-path}/encuesta-satisfaccion/reportes
            excel:
               enabled: true
               output-path: ${schedulers.punche.output-path}/excel/
               file-name: rpt_ficha_encuesta_satisfaccion
               cron: '0 11 8 * * *' # ? 08:00 AM

# ======================================================================================================