  
spring:
   application:
      name: microservice-sigesu
   profiles:
      active: ${PROFILE:dev}

   datasource:
      hikari:
         # Configuración clave para reintentos
         initialization-fail-timeout: -1  # No fallar al inicio
         connection-timeout: 60000
         validation-timeout: 5000
         
         # Pool de conexiones
         maximum-pool-size: 20
         minimum-idle: 5
         idle-timeout: 300000
         max-lifetime: 1200000
         leak-detection-threshold: 60000

   jpa:
      database-platform: org.hibernate.dialect.OracleDialect
      ddl-auto: validate
      show-sql: true
      properties:
         hibernate:
            format_sql: true

   servlet:
     multipart:
       max-request-size: 1GB
       max-file-size: 1GB

logging:
   level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: ${PORT:4004}
  servlet:
    context-path: /api/ms-sigesu/