spring:
   application:
      name: gateway
   profiles:
      active: ${PROFILE:dev}
      
   cloud:
      gateway:
      
         routes:
            -  id: ms-punche
               # uri: lb://microservice-punche
               uri: http://${PUCHE_SERVICE:127.0.0.1}:${PUCHE_PORT:4001}
               predicates:
                  - Path=/api/ms-punche/**
            -  id: ms-cedif
               # uri: lb://microservice-cedif
               uri: http://${CEDIF_SERVICE:127.0.0.1}:${CEDIF_PORT:4002}
               predicates:
                  - Path=/api/ms-cedif/**
            -  id: ms-acercandonos
               # uri: lb://microservice-acercandonos
               uri: http://${ACERCANDONOS_SERVICE:127.0.0.1}:${ACERCANDONOS_PORT:4003}
               predicates:
                  - Path=/api/ms-acercandonos/**
            - id: ms-sigesu
               # uri: lb://microservice-sigesu
              uri: http://${SIGES_SERVICE:127.0.0.1}:${SIGES_PORT:4004}
              predicates:
                 - Path=/api/ms-sigesu/**
            - id: ms-educalle
               # uri: lb://microservice-sigesu
              uri: http://${EDUCALLE_SERVICE:127.0.0.1}:${EDUCALLE_PORT:4005}
              predicates:
                 - Path=/api/ms-educalle/**

         # Configuración global de timeouts
         httpclient:
            connect-timeout: 5000  # Tiempo de espera para establecer la conexión (ms)
            response-timeout: 180s  # Tiempo de espera para recibir la respuesta (ms)

server:
   port: ${PORT:4000}

app:
   security:
      enabled: ${SECURITY_ENABLED:true}
      allowed-origins: ${ALLOWED_ORIGINS:https://srvapp03.inabif.gob.pe}

jwt:
   secret: ${JWT_SECRET_KEY:e28dbddcb0a07a4b8dff3f1c414c49b3bcb61b06af8087a76b707c4fa1d47c3b63433597a71adc8842b720ae3f6b1bb6b1f1f68de64aae6e650786f6864e0a3e}