server:
   ssl:
      enabled: true
      key-store: classpath:certs/inabif.gob.pe.p12
      key-store-password: sigeif
      key-store-type: PKCS12
      key-alias: srvapp03.inabif.gob.pe

spring:
   cloud:
      gateway:
         globalcors:
            cors-configurations:
               '[/**]':
                  allowedOriginPatterns: ${app.security.allowed-origins}
                  allowedMethods: "*"
                  allowedHeaders: "*"
                  allowCredentials: true
                  exposedHeaders:
                     - "Content-Disposition"