
spring:
   cloud:
      gateway:
         globalcors:
            cors-configurations:
               '[/**]':
                  allowedOriginPatterns: "*"
                  allowedMethods: "*"
                  allowedHeaders: "*"
                  allowCredentials: true
         
